cc_library(
    name = "api",
    hdrs = [
        "node.h",
        "visitor.h",
    ],
    include_prefix = "warren/json",
    strip_include_prefix = ".",
    visibility = ["//visibility:public"],
)
