cc_library(
    name = "utils",
    include_prefix = "warren/json/utils",
    visibility = ["//visibility:public"],
    deps = [
        ":exception",
        ":types",
    ],
)

cc_library(
    name = "exception",
    hdrs = [
        "exception.h",
    ],
    include_prefix = "warren/json/utils",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "types",
    hdrs = [
        "types.h",
    ],
    include_prefix = "warren/json/utils",
    visibility = ["//visibility:public"],
)
