#!/usr/bin/env bash
set -e

preset=$1
test=$2

if [[ -z "$preset" ]]; then
  echo "Usage: $0 <preset> [--test]"
  echo "Available presets:"
  echo "  build"
  echo "  build-debug"
  echo "  build-test [--test]"
  echo "  build-test-release [--test]"
  echo "  build-coverage [--test]"
  exit 1
fi

case "${preset}" in
build)
  cmake --preset release
  cmake --build --preset "${preset}"
  ;;
build-debug)
  cmake --preset debug
  cmake --build --preset "${preset}"
  ;;
build-test)
  cmake --preset test
  cmake --build --preset "${preset}"
  if [[ "$test" == "--test" ]]; then
    ctest --preset test
  fi
  ;;
build-test-release)
  cmake --preset test-release
  cmake --build --preset "${preset}"
  if [[ "$test" == "--test" ]]; then
    ctest --preset test-release
  fi
  ;;
build-coverage)
  cmake --preset coverage
  cmake --build --preset "${preset}"
  if [[ "$test" == "--test" ]]; then
    ctest --preset test-coverage
    cmake --build --preset "${preset}" --target report
  fi
  ;;
esac
