cc_library(
    name = "impl",
    visibility = ["//src:__subpackages__"],
    deps = [
        "//src/api",
        "//src/ast",
        "//src/convert",
        "//src/parse",
        "//src/utils",
    ],
)
